Return-Path: <linux-security-module-owner@vger.kernel.org>
X-Original-To: lists+linux-security-module@lfdr.de
Delivered-To: lists+linux-security-module@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 99FD87D0B1
	for <lists+linux-security-module@lfdr.de>; Thu,  1 Aug 2019 00:17:53 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1731448AbfGaWRn (ORCPT
        <rfc822;lists+linux-security-module@lfdr.de>);
        Wed, 31 Jul 2019 18:17:43 -0400
Received: from mail-vs1-f74.google.com ([209.85.217.74]:39886 "EHLO
        mail-vs1-f74.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1731442AbfGaWRm (ORCPT
        <rfc822;linux-security-module@vger.kernel.org>);
        Wed, 31 Jul 2019 18:17:42 -0400
Received: by mail-vs1-f74.google.com with SMTP id p62so18219178vsd.6
        for <linux-security-module@vger.kernel.org>; Wed, 31 Jul 2019 15:17:41 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=google.com; s=20161025;
        h=date:in-reply-to:message-id:mime-version:references:subject:from:to
         :cc;
        bh=QAOtO6nDHkYJ9N49TmHslQT3rCi9zyycpSkmU2B1+ww=;
        b=vsBNHav/9gjDzuC/p4k/ehf5+i2a6WpWSYUinwPcIuMUWwom487dxrSyQaeEFjlILD
         GuWeQYzRIr7AcvrVQ6N9OjJnHtUFW82QbCHblLe/DE5ZDgEbMkl9yz0XaBQlkK3hIrhE
         CRaE81+xyV8pKZV+03bT3FOuVQrkl25+woHlOuMHJqrrquF/lkqyUH+uVl4t0zaG1fPI
         pRfyY6anyqwruTQIYELP/0HE2XyrhE4MuNhGIKY4Yp9/6ptTxjVu3BL6dZdyvYJLtW+2
         iV2zl7xFM87zPbJFwuFGcMhESUot7F/OBzXyBtK/6fgmn8xSe1xZhY/BGloJWxbrUgS/
         jeyA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:date:in-reply-to:message-id:mime-version
         :references:subject:from:to:cc;
        bh=QAOtO6nDHkYJ9N49TmHslQT3rCi9zyycpSkmU2B1+ww=;
        b=QqOHOUZ0vF0s2qVpFp1PZ4GNPCRkw4J7SL3NVpu7lJB24yRgDlorJzRlxjn/xn5Gas
         vcgVzDKMzkBuk/zpE5wIo781tQoZVy01oQihqoSBFUFhNQ1wpQF+4Sqi6I0e2NY7405X
         SfkSP+dz8SFCi5WUHMI/X+5he8+na8kv1Q1zQ+jT6dn9vx9EAU6z5R4UZWGrF56DM+10
         qDmOm5z2oHZxlVuji/Gm4q5OeKepl3+/g3PH71gxaoeAbX9jshlE85RbIuan7h7scC2x
         lXLQM5D069O91pgp5y1k4Fggxw/SPhOquTLegoeE3/OBYPxmujDZS309yA7okZCA6wfN
         509A==
X-Gm-Message-State: APjAAAUTaIXhCtDUstgcbYUD0ZfR02BBu3AszAIoA7Cx1yj1pT2KpQuq
        fTDwj4xiNVAeAndg8jorDiUUQvO6bDXRB9yjw/0SSg==
X-Google-Smtp-Source: APXvYqxUkdmcNxJs0oiJsLLUnAtxrUaESFBqxq+3RtL2nKYerZv5EnzIdcZz6oLV9x/tGowxt8hi1N3I0JS7+k+vkc4ihw==
X-Received: by 2002:ac5:c4cc:: with SMTP id a12mr27573495vkl.28.1564611460638;
 Wed, 31 Jul 2019 15:17:40 -0700 (PDT)
Date:   Wed, 31 Jul 2019 15:16:17 -0700
In-Reply-To: <20190731221617.234725-1-matthewgarrett@google.com>
Message-Id: <20190731221617.234725-30-matthewgarrett@google.com>
Mime-Version: 1.0
References: <20190731221617.234725-1-matthewgarrett@google.com>
X-Mailer: git-send-email 2.22.0.770.g0f2c4a37fd-goog
Subject: [PATCH V37 29/29] lockdown: Print current->comm in restriction messages
From:   Matthew Garrett <matthewgarrett@google.com>
To:     jmorris@namei.org
Cc:     linux-security-module@vger.kernel.org,
        linux-kernel@vger.kernel.org, linux-api@vger.kernel.org,
        Matthew Garrett <matthewgarrett@google.com>,
        David Howells <dhowells@redhat.com>,
        Matthew Garrett <mjg59@google.com>,
        Kees Cook <keescook@chromium.org>
Content-Type: text/plain; charset="UTF-8"
Sender: owner-linux-security-module@vger.kernel.org
Precedence: bulk
List-ID: <linux-security-module.vger.kernel.org>

Print the content of current->comm in messages generated by lockdown to
indicate a restriction that was hit.  This makes it a bit easier to find
out what caused the message.

The message now patterned something like:

        Lockdown: <comm>: <what> is restricted; see man kernel_lockdown.7

Signed-off-by: David Howells <dhowells@redhat.com>
Signed-off-by: Matthew Garrett <mjg59@google.com>
Reviewed-by: Kees Cook <keescook@chromium.org>
---
 fs/proc/kcore.c              | 5 +++--
 security/lockdown/lockdown.c | 8 ++++++--
 2 files changed, 9 insertions(+), 4 deletions(-)

diff --git a/fs/proc/kcore.c b/fs/proc/kcore.c
index ee2c576cc94e..e2ed8e08cc7a 100644
--- a/fs/proc/kcore.c
+++ b/fs/proc/kcore.c
@@ -548,11 +548,12 @@ static int open_kcore(struct inode *inode, struct file *filp)
 {
 	int ret = security_locked_down(LOCKDOWN_KCORE);
 
-	if (ret)
-		return ret;
 	if (!capable(CAP_SYS_RAWIO))
 		return -EPERM;
 
+	if (ret)
+		return ret;
+
 	filp->private_data = kmalloc(PAGE_SIZE, GFP_KERNEL);
 	if (!filp->private_data)
 		return -ENOMEM;
diff --git a/security/lockdown/lockdown.c b/security/lockdown/lockdown.c
index 173191562047..f6c74cf6a798 100644
--- a/security/lockdown/lockdown.c
+++ b/security/lockdown/lockdown.c
@@ -81,10 +81,14 @@ early_param("lockdown", lockdown_param);
  */
 static int lockdown_is_locked_down(enum lockdown_reason what)
 {
+	if (WARN(what >= LOCKDOWN_CONFIDENTIALITY_MAX,
+		 "Invalid lockdown reason"))
+		return -EPERM;
+
 	if (kernel_locked_down >= what) {
 		if (lockdown_reasons[what])
-			pr_notice("Lockdown: %s is restricted; see man kernel_lockdown.7\n",
-				  lockdown_reasons[what]);
+			pr_notice("Lockdown: %s: %s is restricted; see man kernel_lockdown.7\n",
+				  current->comm, lockdown_reasons[what]);
 		return -EPERM;
 	}
 
-- 
2.22.0.770.g0f2c4a37fd-goog

